### PR TITLE
Fix bug where CoverageOverview doesn't match jpdb if new reviews done…

### PR DESCRIPTION
**Pull request by keian-dev**
… after initial cache

### CODE REVIEW

**Comment by kampffrosch94** [comment]
The problem with this approach is that it clobbers the cache every time the user does reviews.
Fetching the vocab list for a deck isn't that expensive individually, but doing it for > 100 decks takes a decent amount of time.

This function also should only cache the vocab list in a deck without their actual state iirc
(DeckWithVocab vs DeckWithVocabState, great naming sense I know)
so changing it should not change this behavior :sweat_smile:

**Comment by keian-dev** [comment]
That makes sense. I'll see if I can take a closer look at this tomorrow and work on making it only update vocab state for the decks.

**Comment by kampffrosch94** [comment]
Don't worry I am fixing this right now.
The problem is here: https://github.com/kampffrosch94/jpdb-deck-manager/blob/6ed5acc8b0f2d9ec49aa321e841ad821d651497b/src/util/jpdb_api.ts#L287-L296
cause i am caching the whole deck and not only its vocab list I also load the *old and outdated* coverage from cache.

**Comment by keian-dev** [comment]
Yea that's what I noticed, I couldn't find a saveDeckToCache call that would execute unless the loadCache failed or it was the first run.
Appreciate you looking into this; the tool is super helpful!

**Pull request closed without merging**
